[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
uv_venv_auto = true

[settings.npm]
bun = true

[tools]
uv = "latest"
bun = "latest"
node = "latest"
pnpm = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:opencode-ai" = "latest"
"pipx:oraios/serena" = "latest"
"npm:@fission-ai/openspec" = "latest"
"pipx:github/spec-kit" = "latest"
"npm:playwright" = {version = "latest", postinstall = "playwright install"}
